[versions]
acf = "1.0.0"
classgraph = "4.8.184"
creative = "1.7.3"
guava = "33.5.0-jre"
jackson = "2.20.1"
kmongo = "5.5.1"
kotlin = "2.3.20-Beta1"
kotlinx = "1.10.2"
kyori = "4.26.1"
logback = "1.5.25"
mockbukkit = "4.100.0"
mockk = "1.14.7"
mongodb = "5.7.0-beta0"
mongojack = "5.0.3"
packetevents = "2.11.1"
paper = "1.21.6-R0.1-SNAPSHOT"
xyz-xenondevs-invui = "2.0.0-beta.1"

[libraries]
acf-paper = { module = "com.github.bananababoo.acf:acf-paper", version.ref = "acf" }
adventure-extra-kotlin = { module = "net.kyori:adventure-extra-kotlin", version.ref = "kyori" }
adventure-gson = { module = "net.kyori:adventure-text-serializer-gson", version.ref = "kyori" }
classgraph = { module = "io.github.classgraph:classgraph", version.ref = "classgraph" }
creative-api = { module = "team.unnamed:creative-api", version.ref = "creative" }
creative-serializer = { module = "team.unnamed:creative-serializer-minecraft", version.ref = "creative" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
invui = { module = "xyz.xenondevs.invui:invui", version.ref = "xyz-xenondevs-invui" }
invui-kotlin = { module = "xyz.xenondevs.invui:invui-kotlin", version.ref = "xyz-xenondevs-invui" }
jackson = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
jackson-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }
kmongo = { module = "org.litote.kmongo:kmongo", version.ref = "kmongo" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-script-runtime = { module = "org.jetbrains.kotlin:kotlin-script-runtime", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
mockbukkit = { module = "org.mockbukkit.mockbukkit:mockbukkit-v1.21", version.ref = "mockbukkit" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mongo-bson = { module = "org.mongodb:bson-kotlinx", version.ref = "mongodb" }
mongo-jackdriver = { module = "org.mongojack:mongojack", version.ref = "mongojack" }
packetevents = { module = "com.github.retrooper:packetevents-spigot", version.ref = "packetevents" }
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
